config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    root 'dashboards#index'
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:destroy, :show]
  end 

  devise_scope :user do 
    post 'users/guest_sign_in', to: 'public/users/sessions#guest_sign_in'
  end 
  
  scope module: :public do
    root to: 'homes#top'
    get 'about', to: 'homes#about'
    get '/search', to: 'searches#search', as: 'search'
    resources :users, only: [:show, :edit, :update, :destroy]
    resources :posts do
      resources :post_comments, only: [:create, :destroy]
    end
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 30 }

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(gravity: :center, resize: "#{width}x#{height}^", crop: "#{width}x#{height}+0+0")
  end

  def self.search_for(content)
    User.where("name LIKE ?", "%#{content}%")
  end

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest 
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!

  def show
    @user = User.find(params[:id]) 
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy 
    redirect_to admin_dashboards_path, notice: 'User was successfully removed.'
  end 
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/show.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card border-0 shadow rounded-4 p-4 text-center">
        <div class="mb-3">
          <%= image_tag @user.get_profile_image(150, 150), class: "rounded-circle img-fluid", alt: "Profile Image", style: "object-fit: cover;" %>
        </div>
        <h3 class="mb-1"><%= @user.name %></h3>
        <div class="d-flex justify-content-center gap-3 mt-3">
          <%= link_to "Delete Account", admin_user_path(@user.id), method: :delete, data: { confirm: "Are you sure you want to delete this account?" }, class: "btn btn-outline-danger" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row mt-5 g-4 justify-content-center">
    <% @user.posts.each do |post| %>
      <div class="col-12 col-md-6 mb-4">
        <div class="card border-0 shadow rounded-4 overflow-hidden h-100">
          <%= link_to post_path(post.id), class: "text-decoration-none text-dark" do %>
            <%= image_tag post.get_image(400, 400), class: "card-img-top object-fit-cover", alt: "Post Image" %>
            <div class="card-body">
              <h5 class="card-title"><%= post.title %></h5>
              <p class="card-text text-muted"><%= truncate(post.body, length: 100) %></p>
              <p><i class="fa-regular fa-comment"></i>  <%= post.post_comments.count %></p>
              <p class="card-text text-end mb-0 d-flex justify-content-end align-items-center gap-2">
                <%= image_tag post.user.get_profile_image(30, 30), class: "rounded-circle", style: "object-fit: cover;" %>
                <span class="text-primary"><%= post.user.name %></span>
              </p>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>