config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    root 'dashboards#index'
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:destroy, :show]
  end 

  devise_scope :user do 
    post 'users/guest_sign_in', to: 'public/users/sessions#guest_sign_in'
  end 
  
  scope module: :public do
    root to: 'homes#top'
    get 'about', to: 'homes#about'
    get '/search', to: 'searches#search', as: 'search'
    resources :users, only: [:show, :edit, :update, :destroy]
    resources :posts do
      resources :post_comments, only: [:create, :destroy]
    end
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-danger">
    <h5 class="alert-heading">Oops! Looks like something went wrong.</h5>
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdminConsole | Aiteru</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/3b4d9a27e8.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-primary">
        <div class="container">
          <%= link_to admin_root_path, class: "navbar-brand p-3 text-light" do %>
            <i class="fa-regular fa-calendar-check"></i> Aiteru Admin Console
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if admin_signed_in? %>
              <li>
                <%= link_to admin_root_path, class: "nav-link text-light" do %>
                  <i class="fa-regular fa-circle-user"></i> Users
                <% end %>
              </li>
              <li>
                <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link text-light" do %>
                <i class="fa-solid fa-right-from-bracket"></i> Log Out
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>

    </header>
    <% if flash[:notice] %>
      <div class="alert alert-success mt-3 shadow" role="alert">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger mt-3 shadow" role="alert">
        <%= flash[:alert] %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aiteru</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/3b4d9a27e8.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
          <%= link_to posts_path, class: "navbar-brand p-3 text-light" do %>
            <i class="fa-regular fa-calendar-check"></i> Aiteru
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <a class="nav-link text-light" data-toggle="collapse" href="#searchForm" role="button" aria-expanded="false" aria-controls="searchForm">
                  <i class="fa-solid fa-magnifying-glass"></i> Search
                </a>
              </li>
              <li>
                <%= link_to user_path(current_user.id), class: "nav-link text-light" do %>
                  <i class="fa-regular fa-circle-user"></i> My Profile
                <% end %>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link text-light dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fa-regular fa-calendar-plus"></i> Plans
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link_to root_path, class: "dropdown-item" do %>
                    Make a plan
                  <% end %>    
                  <div class="dropdown-divider"></div>
                  <%= link_to about_path, class: "dropdown-item" do %>
                    Timeline
                  <% end %>
                </div>
              <li class="nav-item dropdown">
                <a class="nav-link text-light dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fa-regular fa-newspaper"></i> Posts
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link_to new_post_path, class: "dropdown-item" do %>
                    Post
                  <% end %>    
                  <div class="dropdown-divider"></div>
                  <%= link_to posts_path, class: "dropdown-item" do %>
                    Feed
                  <% end %>
                </div>
              </li>
              <li>
                <%= link_to root_path, class: "nav-link text-light" do %>
                <i class="fa-regular fa-heart"></i> Likes
                <% end %>
              </li>
              <li>
                <%= link_to about_path, class: "nav-link text-light" do %>
                <i class="fa-regular fa-circle-question"></i> About
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
                <i class="fa-solid fa-right-from-bracket"></i> Log Out
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to about_path, class: "nav-link text-light" do %>
                <i class="fa-regular fa-circle-question"></i> About
                <% end %>
              </li>
              <li>
                <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
                <i class="fa-regular fa-clipboard"></i> Sign Up
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path, class: "nav-link text-light" do %>
                <i class="fa-solid fa-right-to-bracket"></i> Log In
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
      <div class="collapse bg-light border-top py-3" id="searchForm">
        <div class="container">
          <%= form_with url: search_path, method: :get, local: true do %>
            <div class="form-row">
              <div class="col-md-3 mb-2">
                <%= select_tag :model, options_for_select([['User', 'user'], ['Post', 'post']]), class: "form-control" %>
              </div>
              <div class="col-md-7 mb-2">
                <%= text_field_tag :content, params[:content], placeholder: "Enter a name, title, or keyword…", class: "form-control" %>
              </div>
              <div class="col-md-2 mb-2">
                <%= submit_tag "Search", class: "btn btn-primary btn-block" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>

    </header>
    <% if flash[:notice] %>
      <div class="alert alert-success mt-3 shadow" role="alert">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger mt-3 shadow" role="alert">
        <%= flash[:alert] %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>